apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nksusn/eks-app-backend:v1.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
            - secretRef:
                name: db-secrets
