apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eks-app-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretRef.name }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: eks-app/database
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: eks-app/database
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: eks-app/database
        property: POSTGRES_DB
