apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # You can change this if needed
