replicaCount: 3

image:
  repository: nksusn/eks-app-backend
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

secretRef:
  name: db-secrets
