replicaCount: 2
image:
  repository: nksusn/eks-app-frontend
  tag: v1.0.0
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
backendServiceName: backend
backendServicePort: 3000
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
externalSecrets:
  name: app-secrets
resources: {}